name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - production

permissions:
  contents: read
  pull-requests: write
  checks: write
  deployments: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CODE_QUIZ_B7C01 }}'
          channelId: live
          projectId: code-quiz-b7c01
